name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t bl .
          docker tag bl andreiionut1411/business_logic:latest
          docker push andreiionut1411/business_logic:latest

  deploy_service:
    name: Deploy Service
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Install Curl
        run: sudo apt-get install curl -y

      - name: Trigger Deployment
        run: |
          curl -XPOST http://ip172-18-0-76-cp0akeq91nsg00dg03i0-9000.direct.labs.play-with-docker.com/api/webhooks/d0c5e404-6a1e-4ee2-86c0-21498f3cefcd
